// <auto-generated />
using System;
using CodeAnalyzer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeAnalyzer.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeAnalyzer.Data.FileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("Name");

                    b.Property<DateTime>("SaveTime")
                        .HasColumnName("SaveTime");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("CodeAnalyzer.Data.TaskEntity", b =>
                {
                    b.Property<int>("FileID")
                        .HasColumnName("FileId");

                    b.Property<int>("StringNumber")
                        .HasColumnName("StringNumber");

                    b.Property<string>("Task")
                        .HasColumnName("Task");

                    b.Property<string>("Tooltip")
                        .HasColumnName("Tooltip");

                    b.HasKey("FileID", "StringNumber");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CodeAnalyzer.Data.TaskEntity", b =>
                {
                    b.HasOne("CodeAnalyzer.Data.FileEntity", "File")
                        .WithMany()
                        .HasForeignKey("FileID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
